[project]
name = "visualbrowsernodes-by-lx"
version = "1.1.1"
description = "The ultimate visual browser for your local LoRAs and models! Enjoy a deep Civitai data integration. Take full control of your local library by automatically showing Civitai preview images, loading trigger words, and diving into detailed metadata inspection. Stay organized with intelligent filtering, searching, and the ability to add personal notes to your favorite models. Perfect for content creators, it includes separated SFW and NSFW views to guarantee a safe interface for working, creating videos, or live streaming. Finally your .safetensors files become visible, saving you from scrolling through a dead and unfriendly endless list of models and LoRAs in the default loaders. This suite provides 3 separate nodes: a Civitai Visual Checkpoint Loader, a Civitai Visual Diffusion Model Loader, and a Civitai Visual LoRA Loader."
dependencies = []

[project.urls]
Repository = "https://github.com/LX-ComfyUI/VisualBrowserNodes-by-LX"

[tool.comfy]
PublisherId = "lx-comfyui"
DisplayName = "Civitai Visual Browser & Loader by LX"
Icon = "https://avatars.githubusercontent.com/u/193536438?s=400&u=7271cf118265cfc0d1efe3b2fc7a814b0569095d&v=4"